version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env  # This will load environment variables from the .env file

  backend:
    build: .
    image: backend-app:latest
    ports:
      - "8080:8080"
      - "4053:4053"
      - "3000:3000"
    env_file:
      - .env  # This will load environment variables from the .env file
    depends_on:
      - postgres
